; PlatformIO Project Configuration File
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .

[env]
build_flags =
        '-Wall'
	'-Wno-deprecated'
lib_deps =
	chl33/og3@^0.5.0
	adafruit/Adafruit SHTC3 Library@^1.0.1
	bblanchon/ArduinoJson@^7.0.0
	bakercp/CRC32@^2.0.0
lib_ldf_mode = deep+
check_tool = cppcheck
check_flags =
  cppcheck: --enable=warning,performance,portability,style --inline-suppr --suppress=unusedFunction --suppress=missingInclude --suppress=*:*/.pio/*
check_skip_packages = yes
check_src_filters =
  +<src/>
  +<include/>
  -<.pio/>

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

[env:native]
platform = native
build_flags =
	${env.build_flags}
	'-D NATIVE'
